### ISSUE TITLE
Wildfly 9.0.2.Final fips-compliant-vault + tls issue

### ISSUE THREAD

**Issue by ssill2** [rlucente-se-jboss/fips-compliant-vault#1]
Hi!
I was really excited to have found this project as it is does exactly something I was just trying to get done with the standard vault implementation but realized wasn't supported there.  Our machines are configured with fips mode turned on and the requirement to use the vault mechanism is new for us.

I was able to get this working pretty quickly when it was just the vault being set up, no HTTPS connector at all.  Wildfly comes up flawlessly and my datasource/ldap passwords are properly populated from the vault.

This morning I was going to go ahead and attempt setting up TLS and an https connector and I ran into issues.  I've set up wildfly before without the vault using RedHat EAP instructions for fips(section 4.9.4 on the site mentioned on your github readme).

Prior to any editing of the standalone.xml I simply generated the certificate per the instructions and stored this in the nss keystore the vault setup had created.   At this point I started wildfly and it now failed to start.   if I export the cert to a file and then delete the jbossweb entry out of the keystore wildfly starts again. 

Any idea why this might happen?
Thanks!
The exception thrown is:
2017-01-12 13:46:05,325 ERROR [org.jboss.security.fips.utils.FIPSCryptoUtil] (Controller Boot Thread) failed to unwrap the key: org.mozilla.jss.crypto.TokenException: Cannot match private key for vault cert
	at org.jboss.security.fips.utils.FIPSCryptoUtil.findVaultPrivKeyIndex(FIPSCryptoUtil.java:522)
	at org.jboss.security.fips.utils.FIPSCryptoUtil.unwrapKey(FIPSCryptoUtil.java:309)
	at org.jboss.security.fips.plugins.FIPSCompliantVault.init(FIPSCompliantVault.java:230)
	at org.jboss.as.server.services.security.RuntimeVaultReader.createVault(RuntimeVaultReader.java:96)
	at org.jboss.as.server.services.security.VaultAddHandler.performRuntime(VaultAddHandler.java:84)
	at org.jboss.as.controller.AbstractAddStepHandler.performRuntime(AbstractAddStepHandler.java:276)
	at org.jboss.as.controller.AbstractAddStepHandler$1.execute(AbstractAddStepHandler.java:128)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:803)
	at org.jboss.as.controller.AbstractOperationContext.doCompleteStep(AbstractOperationContext.java:601)
	at org.jboss.as.controller.AbstractOperationContext.completeStepInternal(AbstractOperationContext.java:354)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:330)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1183)
	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:453)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:327)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:313)
	at org.jboss.as.server.ServerService.boot(ServerService.java:384)
	at org.jboss.as.server.ServerService.boot(ServerService.java:359)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:271)
	at java.lang.Thread.run(Thread.java:745)

2017-01-12 13:46:05,326 ERROR [org.jboss.security.fips.plugins.FIPSCompliantVault] (Controller Boot Thread) failed to get admin key from vault
2017-01-12 13:46:05,327 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("core-service" => "vault")]): java.lang.RuntimeException: WFLYSRV0076: Error initializing vault --  org.jboss.as.server.services.security.VaultReaderException: WFLYSRV0227: Vault Reader Exception:
	at org.jboss.as.server.services.security.VaultAddHandler.performRuntime(VaultAddHandler.java:86)
	at org.jboss.as.controller.AbstractAddStepHandler.performRuntime(AbstractAddStepHandler.java:276)
	at org.jboss.as.controller.AbstractAddStepHandler$1.execute(AbstractAddStepHandler.java:128)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:803)
	at org.jboss.as.controller.AbstractOperationContext.doCompleteStep(AbstractOperationContext.java:601)
	at org.jboss.as.controller.AbstractOperationContext.completeStepInternal(AbstractOperationContext.java:354)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:330)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1183)
	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:453)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:327)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:313)
	at org.jboss.as.server.ServerService.boot(ServerService.java:384)
	at org.jboss.as.server.ServerService.boot(ServerService.java:359)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:271)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.as.server.services.security.VaultReaderException: WFLYSRV0227: Vault Reader Exception:
	at org.jboss.as.server.services.security.RuntimeVaultReader.createVault(RuntimeVaultReader.java:98)
	at org.jboss.as.server.services.security.VaultAddHandler.performRuntime(VaultAddHandler.java:84)
	... 14 more
Caused by: org.jboss.security.vault.SecurityVaultException: failed to get admin key from vault
	at org.jboss.security.fips.plugins.FIPSCompliantVault.logErrorAndThrowSVE(FIPSCompliantVault.java:383)
	at org.jboss.security.fips.plugins.FIPSCompliantVault.init(FIPSCompliantVault.java:232)
	at org.jboss.as.server.services.security.RuntimeVaultReader.createVault(RuntimeVaultReader.java:96)
	... 15 more

**Comment by ssill2** [comment]
dug into the code a bit and the fix was pretty simple.  attaching a fix here.

[fips-compliant-vault-multiple_certs_in_store.patch.txt](https://github.com/rlucente-se-jboss/fips-compliant-vault/files/702353/fips-compliant-vault-multiple_certs_in_store.patch.txt)
